#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4{1,0,16.9,4
#
debug.xem4: package/cfg/debug.xem4.mak

clean::
	-$(RM) package/cfg/debug.xem4.mak
