#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = gcc
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/utils.js:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/utils.js
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/xdc.tci:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/xdc.tci
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/template.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/template.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/om2.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/om2.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/xmlgen.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/xmlgen.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/xmlgen2.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/xmlgen2.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/Warnings.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/Warnings.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/IPackage.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/IPackage.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/package.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/package.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/services/global/Clock.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/services/global/Clock.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/services/global/Trace.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/services/global/Trace.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/bld.js:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/bld.js
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/BuildEnvironment.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/PackageContents.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/PackageContents.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/_gen.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/_gen.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Library.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Library.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Executable.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Executable.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Repository.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Repository.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Configuration.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Configuration.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Script.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Script.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Manifest.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Manifest.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Utils.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/Utils.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/ITarget.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/ITarget.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/ITarget2.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/ITarget2.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/ITarget3.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/ITarget3.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/ITargetFilter.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/package.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/bld/package.xs
package.mak: config.bld
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/ITarget.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/ITarget.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/_utils.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/_utils.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/Linux86.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/Linux86.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/Mingw.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/Mingw.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/package.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/package.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/ITarget.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/ITarget.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/GCArmv6.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/GCArmv7A.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/IM.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/IM.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/M3.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/M3.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/A8F.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/A8F.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/A9F.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/A9F.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/A15F.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/A15F.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/A53F.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/A53F.xs
/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/package.xs:
package.mak: /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/package.xs
package.mak: package.bld
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/services/io/File.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/services/io/File.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/services/io/package.xs:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/services/io/package.xs
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
/home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: /home/heo/ti/xdctools_3_50_03_33_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

gnu.targets.arm.M4.rootDir ?= /home/heo/ti/ccsv7/tools/compiler/gcc-arm-none-eabi-6-2017-q1-update
gnu.targets.arm.packageBase ?= /media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.om4g
.PHONY: all,m4g .dlls,m4g .executables,m4g test,m4g
all,m4g: .executables,m4g
.executables,m4g: .libraries,m4g
.executables,m4g: .dlls,m4g
.dlls,m4g: .libraries,m4g
.libraries,m4g: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,m4g
	@$(ECHO) xdc .executables,m4g
	@$(ECHO) xdc .libraries,m4g
	@$(ECHO) xdc .dlls,m4g


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_gcc.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package gcc" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,m4g .dlls: release.pm4g

-include package/cfg/release_pm4g.mak
-include package/cfg/release_pm4g.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/release_pm4g.dep
endif
release.pm4g: package/cfg/release_pm4g.xdl
	@


ifeq (,$(wildcard .libraries,m4g))
release.pm4g package/cfg/release_pm4g.c: .libraries,m4g
endif

package/cfg/release_pm4g.c package/cfg/release_pm4g.h package/cfg/release_pm4g.xdl: override _PROG_NAME := release.xm4g
package/cfg/release_pm4g.c: package/cfg/release_pm4g.cfg
package/cfg/release_pm4g.xdc.inc: package/cfg/release_pm4g.xdl
package/cfg/release_pm4g.xdl package/cfg/release_pm4g.c: .interfaces

clean:: clean,m4g
	-$(RM) package/cfg/release_pm4g.cfg
	-$(RM) package/cfg/release_pm4g.dep
	-$(RM) package/cfg/release_pm4g.c
	-$(RM) package/cfg/release_pm4g.xdc.inc

clean,m4g::
	-$(RM) release.pm4g
.executables,m4g .executables: release.xm4g

release.xm4g: |release.pm4g

-include package/cfg/release.xm4g.mak
release.xm4g: package/cfg/release_pm4g.om4g 
	$(RM) $@
	@$(MSG) lnkm4g $@ ...
	$(RM) $(XDCCFGDIR)$@.map
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -mthumb -march=armv7e-m -nostartfiles -Wl,-static -Wl,--gc-sections     -o $@ package/cfg/release_pm4g.om4g -Wl,-T,package/cfg/release_pm4g.xdl   -L/media/sf_cc3220/simplelink_cc32xx_sdk_1_60_00_04/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/lib/thumb/v7e-m -Wl,--start-group -lgcc -lc -lm -Wl,--end-group --specs=nano.specs -Wl,-Map=$(XDCCFGDIR)/$@.map --specs=nosys.specs
	
release.xm4g: export LD_LIBRARY_PATH=

release.test test,m4g test: release.xm4g.test

release.xm4g.test:: release.xm4g
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 release.xm4g.test
else
	@$(MSG) running $<  ...
	$(call EXEC.release.xm4g, ) 
endif

clean,m4g::
	-$(RM) $(wildcard .tmp,release.xm4g,*)


clean:: clean,m4g

clean,m4g::
	-$(RM) release.xm4g
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
release_pm4g.om4g,copy : package/cfg/release_pm4g.om4g
release_pm4g.sm4g,copy : package/cfg/release_pm4g.sm4g

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,gcc
ifeq (,$(MK_NOGENDEPS))
-include package/rel/gcc.tar.dep
endif
package/rel/gcc/gcc/package/package.rel.xml: package/package.bld.xml
package/rel/gcc/gcc/package/package.rel.xml: package/build.cfg
package/rel/gcc/gcc/package/package.rel.xml: package/package.xdc.inc
package/rel/gcc/gcc/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

gcc.tar: package/rel/gcc.xdc.inc package/rel/gcc/gcc/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/gcc.xdc.inc,package/rel/gcc.tar.dep)


release release,gcc: all gcc.tar
clean:: .clean
	-$(RM) gcc.tar
	-$(RM) package/rel/gcc.xdc.inc
	-$(RM) package/rel/gcc.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
